# Generated by Django 4.1.1 on 2022-09-21 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Start_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=11, verbose_name='время')),
            ],
            options={
                'verbose_name': 'Время занятия',
                'verbose_name_plural': 'Время занятия',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('L', 'лекция'), ('P', ' практическое')], default='P', max_length=1, verbose_name='Занятие')),
                ('course', models.CharField(choices=[('4', 'четвертый'), ('5', 'пятый'), ('6', 'шестой')], default='4', max_length=1, verbose_name='Курс')),
                ('faculty', models.CharField(choices=[('LEK', 'лечебный'), ('PED', 'педиатрический'), ('FOR', 'иностранных учащихся'), ('MIL', 'военно-медицинский')], default='LEK', max_length=3, verbose_name='Факультет')),
                ('language', models.CharField(choices=[('RU', 'русский'), ('EN', 'английский')], default='RU', max_length=2, verbose_name='Язык')),
                ('group', models.CharField(blank=True, max_length=4, verbose_name='Номер группы')),
                ('start_day', models.DateField(verbose_name='Дата занятия')),
                ('end_day', models.DateField(blank=True, null=True, verbose_name='Дата окончания цикла')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.start_class', verbose_name='Начало занятия')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['start_day', 'course', 'faculty'],
            },
        ),
    ]
