# Generated by Django 4.1.1 on 2022-10-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('L', 'лекция'), ('P', ' практическое')], default='P', max_length=1, verbose_name='Категория занятия')),
                ('first_day', models.DateField(verbose_name='Первый день')),
                ('last_day', models.DateField(verbose_name='Последний день')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ['category', 'first_day', 'last_day'],
            },
        ),
    ]
